### PR TITLE
[nav, teleop, esw] new enabled interface

### PR DESCRIPTION
**Pull request by ankithu**
nav code (and teleop and esw code) for the new enabled interface, tested in sim using the teleop GUI because sim update has not been made yet

### CODE REVIEW

**Review by tabiosg — COMMENTED** [review]
what's the diff between this and #1079 ?

**Comment by tabiosg** [comment]
we're no longer using AutonState with the member variable is_auton, right (we're instead using Enable with member variable enabled)? can you do me a favor and change code in jetson/teleop to use Enable instead of AutonState. In the other PR, I think joe forgot

**Review by tabiosg — COMMENTED** [review]
jetson/nav readme will need some updating eventually (it still mentions AutonState)

**Comment by jnnanni** [comment]
> we're no longer using AutonState with the member variable is_auton, right (we're instead using Enable with member variable enabled)? can you do me a favor and change code in jetson/teleop to use Enable instead of AutonState. In the other PR, I think joe forgot (just change line 8 and line 44 in jetson/teleop/src/**main**.py to Enable and AutonState.decode(msg).is_auton to Enable.decode(msg).enabled
> 
> I guess also change NavSimulator.vue

My bad, I can makes the appropriate changes to jetson/teleop this evening. Just to be clear I should push those changes to #1079 and not this PR right?

**Comment by cgiger00** [comment]
> > 
> 
> The difference is just the nav changes have been added to this one. I didn't know exactly how to put my changes in #1079 so I pulled those changes and made a new pr with my changes integrated.

should i close that one then?

**Comment by cgiger00** [comment]
> > we're no longer using AutonState with the member variable is_auton, right (we're instead using Enable with member variable enabled)? can you do me a favor and change code in jetson/teleop to use Enable instead of AutonState. In the other PR, I think joe forgot (just change line 8 and line 44 in jetson/teleop/src/**main**.py to Enable and AutonState.decode(msg).is_auton to Enable.decode(msg).enabled
> > I guess also change NavSimulator.vue
> 
> My bad, I can makes the appropriate changes to jetson/teleop this evening. Just to be clear I should push those changes to #1079 and not this PR right?

you'll want them in this PR i think bc ankith can't push his changes onto yours

**Comment by cgiger00** [comment]
ok this was a lot --edited the science_bridge led stuff, fixed the teleop issue (not sure if you guys want to add something that sets teleop enabled to true in the sa/erd/es guis though so i just set it to default true), fixed issue of gui crashing because the camera stuff hadn't been updated, made the jetson drive ansible services less copy paste, & merged auton-integration with travis free

**Comment by cgiger00** [comment]
closed https://github.com/umrover/mrover-workspace/pull/1079 because it's this one without the bug fixes and merges on top of it

**Review by cgiger00 — APPROVED** [review]
worked well in today's test!

**Comment by tabiosg** [comment]
nice

**Review by tabiosg — APPROVED** [review]

**Pull request merged**
