### PR TITLE
Reverse auton drive

### PR DESCRIPTION
**Pull request by bli76**
Teleop's code to reverse the direction of autonomous drive by request of Auton Nav.

### CODE REVIEW

**Review by CameronTressler — APPROVED** [review]
Zack, can you confirm that up to this point, the rover has been driving exactly how you expect based on what you send? This will drive the rover exactly with the opposite orientation to that

**Comment by zwgold** [comment]
@CameronTressler I can confirm that the rover drives based on what we send, we have not had an issue with this.

**Review by zwgold — APPROVED** [review]
Approved, should be fine when testing

**Review by amszuch — APPROVED** [review]

**Review by cgiger00 — APPROVED** [review]

**Comment by CameronTressler** [comment]
Travis isn't finishing running, and there is no explanation. Will reopen in new PR.

**Pull request closed without merging**
