### PR TITLE
[nav-sim] Remove old nav simulator

### LINKED ISSUE #487: Remove old simulator

### PR DESCRIPTION
**Pull request by amverni**
resolves #487 

Tested by verifying that the new simulator still works properly after deleting the old simulator.

### CODE REVIEW

**Review by raytitan — COMMENTED** [review]
Is there a reason you haven't removed the rest of the files in this directory? Will travis (our automated tester) fail on this?

**Comment by amverni** [comment]
> Is there a reason you haven't removed the rest of the files in this directory? Will travis (our automated tester) fail on this?

No. That's a really good catch! I forgot to remove those files.

**Review by raytitan — APPROVED** [review]
Given you've built and run the new sim fine, this looks good to me!

**Review by atguimond — APPROVED** [review]
Looks good! Is there any reason to keep the old sim around somewhere not in the repository in case the new sim breaks?

**Comment by John-Trager** [comment]
Looks good to me!

**Comment by amverni** [comment]
> Looks good! Is there any reason to keep the old sim around somewhere not in the repository in case the new sim breaks?

If we wanted to do this, we should just keep the old sim around. However, we don't want to do this because we are not maintaining the old sim so newer versions of the nav service won't work with the old sim anymore.

**Comment by amverni** [comment]
It was accidentally closed.

**Review by John-Trager — APPROVED** [review]
Looks good!

**Pull request merged**
