### PR TITLE
[nav] Updating integration to match main

### PR DESCRIPTION
**Pull request by atguimond**
- Gets rid of deprecated obstacle boolean
- Updates simulator package
- Resolves Issue #498

### CODE REVIEW

**Comment by amverni** [comment]
Something doesn't seem right; there are a lot of duplicated commits.

**Comment by amverni** [comment]
I don't think you want to be squashing all of these commits into one thus this PR is not ideal.

**Comment by atguimond** [comment]
I do not see duplicated commits. And why should I not be squashing these commits into one?

**Comment by amverni** [comment]
Can you explain why you _do_ want to squash these commits?

**Comment by atguimond** [comment]
I was just trying to streamline in all of these commits since they have already been made in other places. I can split them up into smaller and more logical commits if that would be better though if you think that would be better.

**Pull request closed without merging**
