### PR TITLE
Remove outdated onboard programs

### PR DESCRIPTION
**Pull request by jubeemer**

### CODE REVIEW

**Comment by jubeemer** [comment]
@amverni Once David accepts his invite as owner I'll request his review on this, he's probably the more appropriate reviewer

**Comment by amverni** [comment]
@DavidSmith166 The auton_light is required for URC, yes. It is not actually maintained by our subteam. For competition we need to visually signal on the rover when we are in autonomy mode (the light being on) as well as signal when we are have finished a "leg" in the autonomy task (the light going off when we enter the done state).

@jubeemer By removing these programs from the repo, our members can no longer test with these components. For this to be feasible, I think the new GPS and IMU programs need to be ready to go soon otherwise we should wait on this PR. Otherwise I think this is good to go.

**Comment by jubeemer** [comment]
> @DavidSmith166 The auton_light is required for URC, yes. It is not actually maintained by our subteam. For competition we need to visually signal on the rover when we are in autonomy mode (the light being on) as well as signal when we are have finished a "leg" in the autonomy task (the light going off when we enter the done state).
> 
> @jubeemer By removing these programs from the repo, our members can no longer test with these components. For this to be feasible, I think the new GPS and IMU programs need to be ready to go soon otherwise we should wait on this PR. Otherwise I think this is good to go.

I talked with David and was under the impression they weren't being used for testing. If they are, I agree there's no reason to remove them now. I'm happy to close this and do the cleanup later.

**Comment by DavidSmith166** [comment]
> 
> 
> > @DavidSmith166 The auton_light is required for URC, yes. It is not actually maintained by our subteam. For competition we need to visually signal on the rover when we are in autonomy mode (the light being on) as well as signal when we are have finished a "leg" in the autonomy task (the light going off when we enter the done state).
> > @jubeemer By removing these programs from the repo, our members can no longer test with these components. For this to be feasible, I think the new GPS and IMU programs need to be ready to go soon otherwise we should wait on this PR. Otherwise I think this is good to go.
> 
> I talked with David and was under the impression they weren't being used for testing. If they are, I agree there's no reason to remove them now. I'm happy to close this and do the cleanup later.

Go ahead and cleanup I don't need any of this

**Pull request merged**
