### PR TITLE
[percep] opencv AR tag debugging tool 

### PR DESCRIPTION
**Pull request by JasonLiu2002**
Shows thresholded matrix and sliders for tuning ARUCO params

### CODE REVIEW

**Comment by cgiger00** [comment]
needs to be updated w auton-integration

**Review by niwhsa9 — APPROVED** [review]
fine w/ me once rebased, unless u want to change to do thresholding urself

**Comment by cgiger00** [comment]
can the conflicts be resolved??

**Comment by JasonLiu2002** [comment]
This only draws the last thresholded matrix, determined using the `adaptiveThreshWinSizeMax` param. ARUCO does several iterations of thresholding between `adaptiveThreshWinSizeMin` and `adaptiveThreshWinSizeMax`, but this should allow you to tune the `adaptiveThreshConstant`. Do we need to see all the other thresholded matrices as well?

**Review by niwhsa9 — APPROVED** [review]
yeah this is much better. @cgiger00 can we get this tested and into main? You guys should try this out on the rover, make sure you know how to use it. Then when you get to URC do this if possible to get the optimal params. In other words, lets make it part of our mock mission too.

**Comment by cgiger00** [comment]
do you want this merged even with the patched version of opencv necessary?

**Comment by JasonLiu2002** [comment]
> so does this now work without a patched version of opencv?

Yes, this is what the latest commit does, although it is untested.

**Comment by cgiger00** [comment]
kk sg, will merge

**Review by cgiger00 — CHANGES_REQUESTED** [review]

**Review by cgiger00 — APPROVED** [review]

**Pull request merged**
