### PR TITLE
[nav] switch from TennisBall LCM to TargetList

### PR DESCRIPTION
**Pull request by amverni**

### CODE REVIEW

**Comment by amverni** [comment]
@calebhar12 Can you look over the CV parts of this patch to ensure we didn't break any of your code?

**Comment by amverni** [comment]
@jubeemer could you double check that the jarvis and teleop commits in here look right. We did not touch those files and to me it seems like it's the exact same code as is already in there so I don't think anything is wrong.

**Comment by aswarner** [comment]
auton code is good, need @calebhar12  to check cv

**Comment by calebhar12** [comment]
cv code looks good!

**Pull request merged**
