### PR TITLE
[nav] Update Gate Traversal Algorithm

### LINKED ISSUE #340: Update Gate Traversal Algorithm
Replace the gate shimmy algorithm with algorithm that drives to far post as an approximation for centering rover between posts.

Have done some integration testing with this

### PR DESCRIPTION
**Pull request by zwgold**
resolves #340

Replace GateShimmy code with code to drive the rover through the gate by having it drive to a post, then drive through the gate.

This PR was originally on main. However, we have closed the original review and moved it to the auton integration testing branch so we can run it before merging it into the main repository.

These changes were tested by using the navigation simulator to mock several different rover scenarios when searching for a waypoint and turning/driving through the gate posts in the correct direction. This includes if the rover passed through the gate in the incorrect direction (and then reorient itself to pass through the correct direction).

### CODE REVIEW

**Comment by aswarner** [comment]
Good style throughout. I tested this on the sim and it worked aside from the occasional "driving off into the sunset" phenomenon that we attribute to the sim not resetting. I tested approaching the gate forwards and backwards. So excited to see this on the rover!

**Comment by aswarner** [comment]
We talked about extending the "center point" distances from the gate after real testing, to allow the rover more distance to cross if necessary.

**Review by aswarner — APPROVED** [review]
Good style throughout. I tested this on the sim and it worked aside from the occasional "driving off into the sunset" phenomenon that we attribute to the sim not resetting. I tested approaching the gate forwards and backwards. So excited to see this on the rover!

**Review by raytitan — APPROVED** [review]

**Comment by so306** [comment]
Nice formatting/spacing, good renaming calls (ex. Post1/2 changed to RightPost/LeftPost). I tested on sim to the best of my ability! Seemed to work.

**Review by so306 — APPROVED** [review]

**Pull request merged**
