### PR TITLE
[sim] Percep noise + GPS noise simulator with threshold adjustment

### PR DESCRIPTION
**Pull request by danieljiang520**

### CODE REVIEW

**Comment by zwgold** [comment]
image
Is there any way to fix this so that we have the decimals truncated? (i.e. increments by 0.1?)

**Review by cgiger00 — APPROVED** [review]
looks good to me

**Review by zwgold — DISMISSED** [review]

**Review by mmartin4972 — CHANGES_REQUESTED** [review]
Why are you merging this into auton-integration? Do you need to integration test it? Can't it just go right into main if it is working good?

**Review by zwgold — APPROVED** [review]

**Review by mmartin4972 — CHANGES_REQUESTED** [review]
There were a few comments that seemed left over from testing. Can you remove those or was there a reason for keeping them in? There were some eslint and console.log comments that I think you can remove.

**Review by mmartin4972 — APPROVED** [review]
Daniel told me the following regarding the eslint comments, so we are going to leave them in. 

> I left the eslint comments in constants.ts because that’s the only way I found to let eslint ignore the “magic numbers” in the constant array

**Review by zwgold — APPROVED** [review]
@cgiger00 seems solid, can probs merge at this point

**Comment by cgiger00** [comment]
is out of date w main...had to remerge it :/

**Review by cgiger00 — APPROVED** [review]
please include screenshots of the sim with it's changes next time!

**Pull request merged**
