### PR TITLE
[teleop] Receive and show search points in GUI

### PR DESCRIPTION
**Pull request by CameronTressler**

### CODE REVIEW

**Comment by CameronTressler** [comment]
image

**Comment by CameronTressler** [comment]
Will automatically update path when auton sends something along /search_points

**Review by cgiger00 — APPROVED** [review]

**Comment by CameronTressler** [comment]
> What was the purpose of the changes to WaypointEditor?

The select function wasn’t doing really anything except logging errors on the console. And we should always be keeping track of longitude in terms of East, not west. These were really just clean up changes as I happened to be looking at these files

**Pull request merged**
