### PR TITLE
[teleop] Add sensor spacing

### PR DESCRIPTION
**Pull request by CameronTressler**

### CODE REVIEW

**Comment by CameronTressler** [comment]
image

**Comment by CameronTressler** [comment]
image

**Review by tabiosg — COMMENTED** [review]
prob looks good, i guess change to urc-22 instead of main?

**Comment by CameronTressler** [comment]
image

**Comment by cgiger00** [comment]
no, it'll be main ☠️

**Review by cgiger00 — APPROVED** [review]

**Comment by cgiger00** [comment]
gyro is backwards

**Review by zwgold — APPROVED** [review]

**Pull request merged**
