### PR TITLE
Visualizer Layers - gpuObsDetection

### PR DESCRIPTION
**Pull request by mberkowitz03**
Pressing buttons 1-6 now shows a different stage in the filtering/debugging process in the viewer. Sorry that all of my latest commits are disgustingly named 'debugging' - was working on Great Lakes.

### CODE REVIEW

**Comment by niwhsa9** [comment]
thank God for git squash

**Comment by qhdwight** [comment]
I rebased this branch, covered in https://github.com/umrover/mrover-workspace/pull/833

**Comment by qhdwight** [comment]
I suggest closing this one and merging the other

**Comment by qhdwight** [comment]
Wait I'm confused, this includes AR stuff too?

**Comment by niwhsa9** [comment]
yeah the AR stuff should really be a separate PR....

**Comment by mberkowitz03** [comment]
OH my bad, I thought this got merged on Sunday

**Comment by mberkowitz03** [comment]
no yea my bad, if quentin rebased, should I just close this PR?

**Pull request closed without merging**
