### PR TITLE
[admin] Added Jarvis launch capabilities

### PR DESCRIPTION
**Pull request by mmartin4972**

### CODE REVIEW

**Comment by cgiger00** [comment]
can this be merged in with auton-integration?

**Comment by mmartin4972** [comment]
> can this be merged in with auton-integration?

I prefer to do incremental merges over a giant auton integration merge. Also, merging this in first shouldn't generate conflicts if you want to do a giant auton integration merge later.

**Comment by cgiger00** [comment]
> > can this be merged in with auton-integration?
> 
> I prefer to do incremental merges over a giant auton integration merge. Also, merging this in first shouldn't generate conflicts if you want to do a giant auton integration merge later.

i mean it's a little late for that, auton-integration is already in a PR to main

**Comment by mmartin4972** [comment]
> > > can this be merged in with auton-integration?
> > 
> > 
> > I prefer to do incremental merges over a giant auton integration merge. Also, merging this in first shouldn't generate conflicts if you want to do a giant auton integration merge later.
> 
> i mean it's a little late for that, auton-integration is already in a PR to main

Gotcha. I didn't realize you had a PR open already for merging into main. I'll close this PR

**Pull request closed without merging**
